version: "3.9"
services:
  improve-text-ai-app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: improve-text-ai-app
    restart: always
    ports:
      - "8000:8000"
    command: >
      sh -c "
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py collectstatic --no-input &&
             daphne -b 0.0.0.0 -p 8000 improve_text_AI.asgi:application"
    volumes:
      - .:/app
      - static-volume:/app/staticfiles
      - media-volume:/app/media
    networks:
      - improve-text-ai-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=improve-text-ai-db
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    depends_on:
      - improve-text-ai-db
  improve-text-ai-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: improve-text-ai-nginx
    restart: always
    ports:
      - 80:80
    networks:
      - improve-text-ai-network
    volumes:
      - static-volume:/var/www/app/staticfiles
      - media-volume:/var/www/app/media
    depends_on:
      - improve-text-ai-app
  improve-text-ai-db:
    image: postgres:15.1-alpine
    container_name: improve-text-ai-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - improve-text-ai-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
volumes:
  static-volume:
  media-volume:
  db:
    driver: local
networks:
  improve-text-ai-network:
    external: true
    driver: bridge
