# Generated by Django 4.2.1 on 2023-05-30 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('TEXT', 'Text'), ('CODE', 'Code')], max_length=20, verbose_name='Type')),
                ('text', models.TextField(verbose_name='Text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_history', related_query_name='improvement_histories', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Improvement history',
                'verbose_name_plural': 'Improvement histories',
                'ordering': ('-id',),
            },
        ),
    ]
