# Generated by Django 4.2.1 on 2023-05-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_improvementhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvementhistory',
            name='responce_text',
            field=models.TextField(default=1, verbose_name='Responce text'),
            preserve_default=False,
        ),
    ]
