# Generated by Django 4.2.1 on 2023-05-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0004_improvementhistory_responce_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='improvementhistory',
            old_name='history_improvment_type',
            new_name='history_improvement_type',
        ),
        migrations.AlterField(
            model_name='improvementhistory',
            name='responce_text',
            field=models.TextField(verbose_name='response text'),
        ),
    ]
