# Generated by Django 4.2.1 on 2023-05-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0005_rename_history_improvment_type_improvementhistory_history_improvement_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='improvementhistory',
            old_name='responce_text',
            new_name='response_text',
        ),
    ]
